In [28]:
import os
from pathlib import Path
import xml.etree.ElementTree as ET
import pandas as pd

In [8]:
data_path = Path('/home/ubuntu/datasets/chem')

In [39]:
pd.read_csv('chem/1976_Sep2016_USPTOgrants_smiles.rsmi', sep='\t')

/home/ubuntu/anaconda3/envs/audio_dl/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ReactionSmiles,PatentNumber,ParagraphNum,Year,TextMinedYield,CalculatedYield
0,[Br:1][CH2:2][CH2:3][OH:4].[CH2:5]([S:7](Cl)(=...,US03930836,NaN,1976,NaN,NaN
1,[Br:1][CH2:2][CH2:3][CH2:4][OH:5].[CH3:6][S:7]...,US03930836,NaN,1976,NaN,NaN
2,[CH2:1]([Cl:4])[CH2:2][OH:3].CCOCC.[CH2:10]([S...,US03930836,NaN,1976,NaN,NaN
3,[Br:1][CH2:2][CH2:3][OH:4].[CH2:5]([S:7](Cl)(=...,US03930839,NaN,1976,NaN,NaN
4,[Br:1][CH2:2][CH2:3][CH2:4][OH:5].[CH3:6][S:7]...,US03930839,NaN,1976,NaN,NaN
...,...,...,...,...,...,...
1808932,Br[C:2]1[CH:3]=[CH:4][C:5]2[NH:6][C:7]3[C:12](...,US09450188B2,551,2016,59%,NaN
1808933,Br[C:2]1[CH:7]=[CH:6][C:5]([C:8]2[C:9]3[C:14](...,US09450188B2,556,2016,80%,77.4%
1808934,Br[C:2]1[CH:7]=[CH:6][C:5]([C:8]2[CH:21]=[CH:2...,US09450188B2,574,2016,61%,NaN
1808935,Br[C:2]1[CH:3]=[C:4]([C:8]2[CH:21]=[CH:20][C:1...,US09450188B2,608,2016,70%,69.5%
1808936,Br[C:2]1[CH:3]=[C:4]([C:8]2[CH:21]=[CH:20][C:1...,US09450188B2,625,2016,60%,58.7%

In [41]:
pd.read_csv('chem/2001_Sep2016_USPTOapplications_smiles.rsmi', sep='\t')

/home/ubuntu/anaconda3/envs/audio_dl/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ReactionSmiles,PatentNumber,ParagraphNum,Year,TextMinedYield,CalculatedYield
0,[C:1]([C:5]1[CH:10]=[CH:9][C:8]([OH:11])=[CH:7...,US20010000035A1,7.0,2001,NaN,NaN
1,[Cl-].[Al+3].[Cl-].[Cl-].[Cl:5][CH2:6][CH2:7][...,US20010000038A1,256.0,2001,86%,86.9%
2,[Al+3].[Cl-].[Cl-].[Cl-].[Cl:5][CH2:6][CH2:7][...,US20010000038A1,259.0,2001,95%,NaN
3,[Cl:1][CH2:2][CH2:3][CH2:4][C:5]([C:7]1[CH:12]...,US20010000038A1,285.0,2001,NaN,NaN
4,[Cl:1][CH2:2][CH2:3][CH2:4][C:5]([C:7]1[CH:12]...,US20010000038A1,287.0,2001,100%,100.9%
...,...,...,...,...,...,...
1939248,[NH:1]1[C:9]2[C:4](=[CH:5][CH:6]=[C:7]([NH:10]...,US20160272617A1,2361,2016,NaN,NaN
1939249,[OH:1][CH:2]1[CH2:5][CH:4]([NH:6][C:7]([C:9]2[...,US20160272617A1,2365,2016,NaN,NaN
1939250,C(OC([NH:8][CH2:9][C@H:10]1[CH2:15][CH2:14][C@...,US20160272617A1,2373,2016,NaN,NaN
1939251,[CH:1]1([NH:4][C:5]([C:7]2[CH:12]=[CH:11][C:10...,US20160272617A1,2377,2016,NaN,NaN
1939252,[OH-].[Li+].FC(F)(F)C(O)=O.[NH2:10][CH2:11][C@...,US20160272617A1,2381,2016,NaN,NaN